[2022-09-05T21:00:59.067+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2022-09-02T00:00:00+00:00 [queued]>
[2022-09-05T21:00:59.081+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2022-09-02T00:00:00+00:00 [queued]>
[2022-09-05T21:00:59.081+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:00:59.081+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-05T21:00:59.082+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:00:59.105+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-09-02 00:00:00+00:00
[2022-09-05T21:00:59.111+0000] {standard_task_runner.py:52} INFO - Started process 11599 to run task
[2022-09-05T21:00:59.115+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_table', 'scheduled__2022-09-02T00:00:00+00:00', '--job-id', '397', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operators.py', '--cfg-path', '/tmp/tmpfo3fjjox', '--error-file', '/tmp/tmpxgkpl80_']
[2022-09-05T21:00:59.116+0000] {standard_task_runner.py:80} INFO - Job 397: Subtask insert_into_table
[2022-09-05T21:00:59.233+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2022-09-02T00:00:00+00:00 [running]> on host c033faf33c57
[2022-09-05T21:00:59.428+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ancordss
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v02
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-02T00:00:00+00:00
[2022-09-05T21:00:59.458+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-05T21:00:59.468+0000] {sql.py:315} INFO - Running statement: insert into dag_runs (dt, dag_id) values ('2022-09-02', 'dag_with_postgres_operator_v02'), parameters: None
[2022-09-05T21:00:59.473+0000] {sql.py:324} INFO - Rows affected: 1
[2022-09-05T21:00:59.512+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_table, execution_date=20220902T000000, start_date=20220905T210059, end_date=20220905T210059
[2022-09-05T21:00:59.576+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05T21:00:59.653+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
