[2022-09-05T21:10:05.922+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-09-05T21:10:05.941+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-09-05T21:10:05.941+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:10:05.941+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-05T21:10:05.942+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:10:05.969+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-09-01 00:00:00+00:00
[2022-09-05T21:10:05.978+0000] {standard_task_runner.py:52} INFO - Started process 12050 to run task
[2022-09-05T21:10:05.981+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '419', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operators.py', '--cfg-path', '/tmp/tmpuq4gfuug', '--error-file', '/tmp/tmp_lggaohj']
[2022-09-05T21:10:05.982+0000] {standard_task_runner.py:80} INFO - Job 419: Subtask insert_into_table
[2022-09-05T21:10:06.162+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2022-09-01T00:00:00+00:00 [running]> on host c033faf33c57
[2022-09-05T21:10:06.282+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ancordss
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v03
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-09-05T21:10:06.297+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-05T21:10:06.305+0000] {sql.py:315} INFO - Running statement: insert into dag_runs (dt, dag_id) values ('2022-09-01', 'dag_with_postgres_operator_v03'), parameters: None
[2022-09-05T21:10:06.307+0000] {sql.py:324} INFO - Rows affected: 1
[2022-09-05T21:10:06.329+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, execution_date=20220901T000000, start_date=20220905T211005, end_date=20220905T211006
[2022-09-05T21:10:06.366+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05T21:10:06.448+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
