[2022-09-05T18:08:09.350+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_05.get_name manual__2022-09-05T18:03:06.929909+00:00 [queued]>
[2022-09-05T18:08:09.363+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_05.get_name manual__2022-09-05T18:03:06.929909+00:00 [queued]>
[2022-09-05T18:08:09.363+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T18:08:09.363+0000] {taskinstance.py:1369} INFO - Starting attempt 2 of 6
[2022-09-05T18:08:09.364+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T18:08:09.382+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): get_name> on 2022-09-05 18:03:06.929909+00:00
[2022-09-05T18:08:09.386+0000] {standard_task_runner.py:52} INFO - Started process 3780 to run task
[2022-09-05T18:08:09.389+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_05', 'get_name', 'manual__2022-09-05T18:03:06.929909+00:00', '--job-id', '328', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmp5d1obq71', '--error-file', '/tmp/tmp7fgqs0u9']
[2022-09-05T18:08:09.390+0000] {standard_task_runner.py:80} INFO - Job 328: Subtask get_name
[2022-09-05T18:08:09.469+0000] {task_command.py:371} INFO - Running <TaskInstance: our_dag_with_python_operator_05.get_name manual__2022-09-05T18:03:06.929909+00:00 [running]> on host c033faf33c57
[2022-09-05T18:08:09.571+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ancordss
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_05
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T18:03:06.929909+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-05T18:03:06.929909+00:00
[2022-09-05T18:08:09.623+0000] {python.py:173} INFO - Done. Returned value was: None
[2022-09-05T18:08:09.642+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=our_dag_with_python_operator_05, task_id=get_name, execution_date=20220905T180306, start_date=20220905T180809, end_date=20220905T180809
[2022-09-05T18:08:09.685+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05T18:08:09.731+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
