[2022-09-05T21:01:00.527+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05T21:01:00.546+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05T21:01:00.547+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:01:00.547+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-05T21:01:00.547+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:01:00.575+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-09-04 00:00:00+00:00
[2022-09-05T21:01:00.582+0000] {standard_task_runner.py:52} INFO - Started process 11609 to run task
[2022-09-05T21:01:00.586+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_table', 'scheduled__2022-09-04T00:00:00+00:00', '--job-id', '399', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operators.py', '--cfg-path', '/tmp/tmphq0b9dsb', '--error-file', '/tmp/tmpuu_zmpjz']
[2022-09-05T21:01:00.587+0000] {standard_task_runner.py:80} INFO - Job 399: Subtask insert_into_table
[2022-09-05T21:01:00.698+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_table scheduled__2022-09-04T00:00:00+00:00 [running]> on host c033faf33c57
[2022-09-05T21:01:00.838+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ancordss
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v02
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05T21:01:00.855+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-05T21:01:00.862+0000] {sql.py:315} INFO - Running statement: insert into dag_runs (dt, dag_id) values ('2022-09-04', 'dag_with_postgres_operator_v02'), parameters: None
[2022-09-05T21:01:00.863+0000] {sql.py:324} INFO - Rows affected: 1
[2022-09-05T21:01:00.888+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_table, execution_date=20220904T000000, start_date=20220905T210100, end_date=20220905T210100
[2022-09-05T21:01:00.928+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05T21:01:00.981+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
